### PR TITLE
Handle unhandled errors in `socket.reconnectStrategry`

### LINKED ISSUE #2234: error in reconnecting event listener silently prevents reconnection
As I commented on #2032, I discovered that if the `reconnecting` event listener throws an error, it will silently prevent reconnection from happening.  No error message will be logged, and there is no indication anything has gone wrong except that it just doesn't ever attempt to reconnect.  I think it would be helpful if an error message was logged in this situation and the reconnection was able to proceed.

This is easiest to reproduce using Heroku's Redis server, which by default closes all connections after 5 minutes of inactivity.

**Environment:**
 - **Node.js Version**: 16.15.1
 - **Redis Server Version**: 6.2.3 (Heroku)
 - **Node Redis Version**: 4.2.0
 - **Platform**: MacOS 12.5

**Reproducer:**

```javascript
import { createClient } from "redis";

export const client = createClient({ url: process.env.REDIS_URL });

client.on('error', err => console.log(`Redis error: ${err}`));
// the below line works fine
//client.on('reconnecting', () => console.log('Redis reconnecting'));
// the below line causes an error, which is swallowed and silently prevents reconnect
client.on('reconnecting', (foo) => console.log('Redis reconnecting' + foo.bar));
client.on('connect', () => console.log('Redis connected'));
client.on('ready', () => console.log('Redis ready'));
client.on('end', () => console.log('Redis connection closed'));

await client.connect();
```

Output in the broken case:
```
Redis connected
Redis ready
Redis error: Error: Socket closed unexpectedly
```

Output in the working case (uncomment the working line and comment the broken line):
```
Redis connected
Redis ready
Redis error: Error: Socket closed unexpectedly
Redis reconnecting
Redis connected
Redis ready
```

Thank you.

### LINKED ISSUE #2237: Not working as expected in rainy days
On redis connection failure, I do not get exception.
I have upgraded to redis 4.2.0 with the following lambda :

```
export const handler = async (
    event: APIGatewayEvent, context: Context, callback: APIGatewayProxyCallback
) => {
    try {
        console.log(`Lambda triggered with event: ${JSON.stringify(event)}`);
        context.callbackWaitsForEmptyEventLoop = false;
        const redisClient = redis.createClient({
            socket: {
                host: '127.0.0.1',
                port: 6379,
                reconnectStrategy: function (retriesAttemptedSoFar: number): number | Error {
                    if (retriesAttemptedSoFar > 3) {
                        // End reconnecting with error
                        return new Error(`Redis retry attempt=${retriesAttemptedSoFar}`);
                    }
                    console.info(` try reconnect after ${Math.min(retriesAttemptedSoFar * 10, 30)}ms`);
                    // reconnect after
                    return Math.min(retriesAttemptedSoFar * 10, 30);
                }
            },
        });
        redisClient.on('ready', () => {
            console.log(`Got "ready" event from Redis. Connection established.`);
        });
        redisClient.on('connect', () => {
            console.log(`Got "connect" event from Redis. Stream is connected to the server`);
        });
        redisClient.on('error', (err) => {
            console.log(`Got an ERROR from Redis. Details: ${err.message}`);
        });
        await redisClient.connect();
        let serverStates : string[] = [];
        const MAX_RETRIES = 3;
        let i = 0;
        while (i < MAX_RETRIES) {
            try {
                serverStates = await redisClient.lRange('123', 0, -1);
            } catch (e) {
                i++;
                const logMessage = i < MAX_RETRIES ?
                    `attempt ${i}: Failed to store message. Trying again...` :
                    `attempt ${i}: Failed to store message. All attempts failed`;
                console.warn(logMessage);
                await new Promise(resolve => setTimeout(resolve, 10));
            }
        }
        if (i >= MAX_RETRIES) {
            throw new Error('Exceeded Max Attempts to store message in Redis');
        }
        console.log(`ServerStates: ${JSON.stringify(serverStates)}`);

        console.log(`${JSON.stringify(event)} Lambda finished successfully`);
        callback(null, {
            statusCode: 200,
            body: 'theResult'
        });
    } catch (e) {
        const error = e as Error;
        console.error(`Lambda execution failed. Got error: ${error.message}`);
        callback(error);
    }
}
```

- If I do not get exception from redis, all works.
- If I do not specify reconnectStrategy and redis connection fail, the code trys to reconnect inifinitly.
- If redis connection fail with reconnectStrategy code, lambda gets to the catch section after 3 re-connections as expected.

### **The problem is** : If I succeed to connect to redis, but before _lrage_ redis stops (redis connection fail Socket closed unexpectedly) redis client reconnects for 3 times as written in reconnectStrategy, and after the 3 re-connects, the code stops and do not get to the catch section, ending the lambda as successfully finished. 
How can I get to the exception section in this scenario ? 
In redis 3.1.X, in similar case lambda finished with exception.

**Environment:**
 - **Node.js Version**:  v14.1.0
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.2.0
 - **Platform**: Windows 10

### PR DESCRIPTION
**Pull request by leibale**
#2205 #2032

close #2234
fix #2237

### CODE REVIEW

File: packages/client/lib/client/socket.ts [hunk 1]
```diff
@@ -5,11 +5,13 @@ import { RedisCommandArguments } from '../commands';
 import { ConnectionTimeoutError, ClientClosedError, SocketClosedUnexpectedlyError, ReconnectStrategyError } from '../errors';
 import { promiseTimeout } from '../utils';
 
+type ReconnectStrategy = (retires: number) => number | Error;
```
Comment (BartoszMarganiec) [inline packages/client/lib/client/socket.ts:8]: Typo - retries

**Comment by just4fun** [comment]
Hi @leibale , thanks for the fix. Do you have any plan to release it recently? as our new product is facing this issue with the latest `node-redis`.

**Comment by leibale** [comment]
Hi @just4fun, I'm planning to release it this week.
Wanna give it a shot before I release it to npm?
