### PR TITLE
fix(client): add type annotations

### LINKED ISSUE #2933: 5.0.0 HGETALL returns type doesn't make sens in TS
## Since the 5.0.0 I'm having typescript error when using HGETALL

**In the documentation :** 
```
Replies will be transformed into useful data structures:

await client.hGetAll("key"); // { field1: 'value1', field2: 'value2' }
await client.hVals("key"); // ['value1', 'value2']
```

**In VS Code:** 
```
const data = await this.redisClient.HGETALL(group);
return Object.entries(data).map((entry) => {
    const value = parseFloat(entry[1]);
                             ^^^^^^^^^
    return { key: entry[0], value: isNaN(value) ? null : value };
});

```

> Argument of type '{ toString: {}; }' is not assignable to parameter of type 'string'.
> (parameter) entry: [string, {
>     toString: {};
> }]

**In 4.7.0, the TS type of the entry was:** 
```(parameter) entry: [string, string]```

### PR DESCRIPTION
**Pull request by nkaradzhov**
Fix type parameter for transformTuplesReply in CONFIG_GET and HGETALL commands

fixes #2933

### Description

> Describe your pull request here

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Review by htemelski — APPROVED** [review]

File: packages/client/lib/commands/CONFIG_GET.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export default {
     parser.pushVariadic(parameters);
   },
   transformReply: {
-    2: transformTuplesReply,
+    2: transformTuplesReply<BlobStringReply>,
```
Comment (htemelski) [inline packages/client/lib/commands/CONFIG_GET.ts:13]: Maybe we should check the other commands for similar issues

Comment (nkaradzhov) [reply packages/client/lib/commands/CONFIG_GET.ts:13]: thats twe only 2 places i saw transformTuplesReply being used in this way. everywhere else, the types look to be picking up ok
