### PR TITLE
fix(client): make unstable cmds throw

### LINKED ISSUE #2989: Unstable core commands dont throw without unstableResp3
### Description

As per [the docs](https://github.com/redis/node-redis/blob/master/docs/v5.md#unstable-module-commands), 

> Some Redis module commands have unstable RESP3 transformations. These commands will throw an error when used with RESP3 unless you explicitly opt in to using them by setting unstableResp3: true in your client configuration

- update docs, remove `module`
- fix commands

### Node.js Version

_No response_

### Redis Server Version

_No response_

### Node Redis Version

_No response_

### Platform

_No response_

### Logs

```bash

```

### PR DESCRIPTION
**Pull request by nkaradzhov**
As per [the docs](https://github.com/redis/node-redis/blob/master/docs/v5.md), unstableResp3 commands should throw when client is created with { RESP: 3, unstableResp3: false|undefined }

fixes #2989

---

### Checklist

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

File: packages/client/lib/commander.ts [hunk 1]
```diff
@@ -38,7 +38,11 @@ export function attachConfig<
     Class: any = class extends BaseClass {};
 
   for (const [name, command] of Object.entries(commands)) {
-    Class.prototype[name] = createCommand(command, RESP);
+    if (config?.RESP == 3 && command.unstableResp3 && !config.unstableResp3) {
```
Comment (bobymicroby) [inline packages/client/lib/commander.ts:41]: @nkaradzhov I just remembered that I saw [this](https://github.com/bobymicroby/node-redis/blob/b33a662e501fcea56aa27d7e90ff604b9f965183/packages/client/lib/commander.ts#L49) piece of code which was supposed to attach a command that throws an error. Maybe we can fix that code instead.

Comment (nkaradzhov) [reply packages/client/lib/commander.ts:41]: @bobymicroby [this is working properly](https://github.com/bobymicroby/node-redis/blob/b33a662e501fcea56aa27d7e90ff604b9f965183/packages/client/lib/commander.ts#L49). The problem is that it is executed only for module commands. And we have XREAD and XREADGROUP as part of the main client. So we should add the same logic in the place we attach the core functions as well

**Review by bobymicroby — APPROVED** [review]
lgtm

File: packages/client/lib/commander.ts (hunk 1 above)
Comment (bobymicroby) [reply packages/client/lib/commander.ts:41]: got it
